### ISSUE TITLE
Incompatible flake8 versions

### ISSUE THREAD

**Issue by rmk135** [snoack/flake8-per-file-ignores#10]
Hi,

I use latest `flake8` and get: 

```
ERROR: flake8-per-file-ignores 0.8.1 has requirement flake8<3.7,>=3, but you'll have flake8 3.8.3 which is incompatible.
```

Fix if possible, please.

**Comment by jonafato** [comment]
From the README:

>This flake8 extension has been discontinued in favour of the per-file-ignores option built into flake8 3.7.0 and above. But be aware that the built-in option uses different syntax.

This is now built into Flake8 and can be configured with the [`per-file-ignores` option](https://flake8.pycqa.org/en/latest/user/options.html#cmdoption-flake8-per-file-ignores).

**Comment by rmk135** [comment]
🤦 I didn't notice this.

Thank you
