### ISSUE TITLE
Publish source distributions to PyPI

### ISSUE THREAD

**Issue by jonafato** [snoack/flake8-per-file-ignores#4]
In cases where wheel support is not available, flake8-per-file-ignores cannot be installed from PyPI. Please publish `sdist` distributions in addition to wheels to support those systems. The official Python packaging guide provides documentation on [creating](https://packaging.python.org/tutorials/distributing-packages/#packaging-your-project) and [uploading](https://packaging.python.org/tutorials/distributing-packages/#upload-your-distributions) distributions.

**Comment by snoack** [comment]
Can you explain (or provide a link to a resource explaining), why/when a universal wheel isn't sufficient? I suppose, this was the case, with ancient versions of pip. But (when) is this still a problem in practice?

**Comment by jonafato** [comment]
[pypi2nix](https://github.com/garbas/pypi2nix), for example, requires that packages be built from source. Other tools may have similar restrictions. Additionally, the [packaging docs](https://packaging.python.org/tutorials/distributing-packages/#source-distributions) recommend publishing source distributions:
>Minimally, you should create a Source Distribution

**Comment by snoack** [comment]
There you go. I uploaded a source distribution PyPI.

**Comment by jonafato** [comment]
Thanks!
