### ISSUE TITLE
End-of-line comment results in X100 Superfluous per-file-ignores

### ISSUE THREAD

**Issue by aguynamedben** [snoack/flake8-per-file-ignores#5]
Hi, thanks for working on this library. I wanted to report a small bug that isn't a show-stopper but was unexpected to me. If I add a comment at the end of the line, I get the `X100 Superfluous per-file-ignores` error unexpectedly.

#### Example

In my tox.ini:
```ini
[flake8]
per-file-ignores =
    land/models/__init__.py: F401  # module imported but unused
```

results in:
```
X100 Superfluous per-file-ignores for F401  # module imported but unused
```

If I move the comment above...
```ini
[flake8]
per-file-ignores =
    # module imported but unused
    land/models/__init__.py: F401
```

It works as expected.

I use end-of-line comments in other parts of my tox.ini to comment what codes mean, but it broke with flake8-per-file-ignores.

Thanks again for the time you spend working on this and making it public.

**Comment by snoack** [comment]
If this is a bug (i.e. unintended behavior, not compliant to INI format) then this would be a bug in Python's `configparser` module. Apparently, it doesn't consider it a comment, but part of the string. I could work around it, but I'm not convinced (yet) if this is worth it (or even appropriate).

**Comment by aguynamedben** [comment]
Okay. For reference, I'm able to add end-of-line comments in other areas of my tox.ini unrelated to this library, here's my whole tox.ini:

```ini
[flake8]
ignore =
    ###
    # From pyflakes/flake8
    # http://flake8.pycqa.org/en/latest/user/error-codes.html?highlight=codes
    #

    # (none)

    ##################
    # From pycodestyle
    # https://pycodestyle.readthedocs.io/en/latest/intro.html#error-codes
    #

    # Whitespace warning
    W293, # blank line contains whitespace

    ##########################
    # From flake8_import_order
    # https://github.com/PyCQA/flake8-import-order#warnings
    #

    I100, # Your import statements are in the wrong order.
    I201  # Additional newline in a group of imports.

    #################
    # From pydocstyle
    # http://www.pydocstyle.org/en/2.1.1/error_codes.html
    #

    # Missing Docstrings
    D100,D101,D102,D103,D104,D105,D106,D107

    # Whitespace Issues
    D200,D202,D204,D205,

    # Quotes Issues
    D300,

    # Docstring Content Issues
    D400,D401,D403,

per-file-ignores =
    # pyflakes/flake8 - module imported but unused
    */__init__.py: F401,
    # pycodestyle - line too long
    */urls.py: E501

exclude =
    # No need to traverse our git directory
    .git,
    # There's no value in checking cache directories
    __pycache__

max-complexity = 10

max-line-length = 120
```

This works. But it breaks if I move comments in the `per-file-ignores` section to be end-of-line, as they are in the other sections.

It's not a show-stopper for me, I just wanted to let you know in case other people come across this. Feel free to close if you feel that's appropriate. Thanks again for making this.

**Comment by snoack** [comment]
Note that the `ignore` option doesn't support end-of-line comments either. However, the way its value is split up, `W293, # blank line contains whitespace` for example tells flake8 to ignore any error code that starts with `W239`, `#`, `blank`, `line`, `contains` or `whitespace`. While the additional tokens don't have any effect here (since no valid error code can start with any of them), it can cause unintended effects in other cases, e.g. `Z100 # is redundant with Y200` will cause both `Z100` and `Y200` to be ignored.

**Comment by jonafato** [comment]
For reference, the [`ConfigParser` docs](https://docs.python.org/3/library/configparser.html) state this:

>By default inline comments are disabled and '#' and ';' are used as prefixes for whole line comments.

Flake8 [uses the defaults](https://github.com/PyCQA/flake8/blob/3530870679ddb93ade9326d9e5d932596b66e8b9/src/flake8/options/config.py#L63), so it doesn't seem like there's upstream support for inline comments at this time.
